name: Build & Publish Docker image

on: 
  push:
    branches:
      - master
  release:
    types: [published]

env:
  IS_RELEASE: ${{github.event_name != 'release'}}

jobs:
  docker-publish:
    runs-on: ubuntu-latest
    timeout-minutes: 59
    steps:
      # -
      #   name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2
      # -
      #   name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2
      # -
      #   name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: always
        run: echo ${{env.IS_RELEASE}}
      -
        name: if true
        if: env.IS_RELEASE == 'true'
        run: echo 'It is a release'
      -
        name: if false
        if: env.IS_RELEASE == 'false'
        run: echo 'not a release'
      - 
        name: Compute tags
        if: env.IS_RELEASE
        run: echo "TAG_VERSION=$(release='${{github.event.release.tag_name}}' && echo ${release:1})" >> $GITHUB_ENV
      -
        name: Print tags
        run: echo ${{(env.IS_RELEASE && format('gruxer/prism:{0},gruxer/prism:latest', env.TAG_VERSION)) || 'gruxer/prism:master'}}
      # -
      #   name: Build and Push
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     push: true
      #     tags: ${{(env.IS_RELEASE == 'release' && format('gruxer/prism:{0},gruxer/prism:latest', env.TAG_VERSION)) || 'gruxer/prism:master'}}
      #     platforms: linux/amd64
      #     build-args: BUILD_TYPE=production